import React, { useContext, useState } from "react";
import { Button, IconButton, InputAdornment, TextField } from "@mui/material";
import { EmailOutlined, LockOutlined, Visibility, VisibilityOff } from "@mui/icons-material";
import { Link, useNavigate } from "react-router-dom";
import { MyContext } from "../../App";
import api from "../../api/axios";
import AuthLayout from "../../components/Auth/AuthLayout";

const Login = () => {
  const [showPassword, setShowPassword] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState("");
  const [fields, setFields] = useState({ email: "", password: "" }); const navigate = useNavigate(), context = useContext(MyContext);
  const submit = async (e) => { e.preventDefault(); setError(""); if (!fields.email || !fields.password) return setError("Please enter your email and password."); setLoading(true); try { const res = await api.post("/user/login", fields); if (res.data.success) { const { accessToken, refreshToken } = res.data.data; const user = (await api.get("/user/user-details", { headers: { Authorization: `Bearer ${accessToken}` } })).data.data; localStorage.setItem("accessToken", accessToken); localStorage.setItem("refreshToken", refreshToken); localStorage.setItem("user", JSON.stringify(user)); context?.setUser?.(user); context?.setIsLogin?.(true); context?.openAlertBox("success", "Welcome back!"); navigate(user.role === "ADMIN" ? "/admin" : "/"); } } catch (err) { setError(err.response?.data?.message || "We couldn't sign you in. Please try again."); } finally { setLoading(false); } };
  return <AuthLayout title="Welcome back" description="Sign in to continue your coffee journey."><form className="auth-form" onSubmit={submit}>{error && <p className="auth-alert" role="alert">{error}</p>}<label className="auth-field"><span className="auth-label">Email address</span><TextField fullWidth type="email" autoComplete="email" placeholder="you@example.com" value={fields.email} onChange={(e) => setFields({ ...fields, email: e.target.value })} slotProps={{ input: { startAdornment: <InputAdornment position="start"><EmailOutlined fontSize="small" /></InputAdornment> } }} /></label><label className="auth-field"><span className="auth-label">Password</span><TextField fullWidth type={showPassword ? "text" : "password"} autoComplete="current-password" placeholder="Enter your password" value={fields.password} onChange={(e) => setFields({ ...fields, password: e.target.value })} slotProps={{ input: { startAdornment: <InputAdornment position="start"><LockOutlined fontSize="small" /></InputAdornment>, endAdornment: <InputAdornment position="end"><IconButton aria-label="Toggle password visibility" onClick={() => setShowPassword(!showPassword)} edge="end">{showPassword ? <VisibilityOff /> : <Visibility />}</IconButton></InputAdornment> } }} /></label><div className="auth-row"><span /><Link className="auth-link" to="/forgot-password">Forgot password?</Link></div><Button className="auth-submit" type="submit" fullWidth disabled={loading}>{loading ? "Signing in..." : "Sign in"}</Button></form><p className="auth-footer">New to Rahila Coffee? <Link className="auth-link" to="/signUp">Create an account</Link></p></AuthLayout>;
};
export default Login;
